const STATUS_CODE_CREATED = 201;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_CONFLICT = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  STATUS_CODE_BAD_REQUEST,
  STATUS_CODE_CONFLICT,
  STATUS_CODE_CREATED,
  INTERNAL_SERVER_ERROR,
};
